2022-08-31 15:42:03,384 whq日志 INFO test_login.py-45 line :************测试用例开始执行************
2022-08-31 15:42:03,384 whq日志 INFO test_login.py-46 line :测试数据为：{'username': 'whq', 'password': '123456a', 'check': '{"errcode":0,"errmsg":"登录成功"}'}
2022-08-31 15:42:03,384 whq日志 INFO test_login.py-48 line :实际运行结果为：{'errcode': 0, 'errmsg': '登录成功'}
2022-08-31 15:42:03,384 whq日志 INFO test_login.py-55 line :断言成功，用例通过！
2022-08-31 15:42:03,384 whq日志 INFO test_login.py-56 line :************测试用例执行结束************
2022-08-31 15:42:03,384 whq日志 INFO test_login.py-45 line :************测试用例开始执行************
2022-08-31 15:42:03,385 whq日志 INFO test_login.py-46 line :测试数据为：{'username': 'whq1', 'password': 123456, 'check': '{"errcode":1,"errmsg":"账号或密码错误"}'}
2022-08-31 15:42:03,385 whq日志 INFO test_login.py-48 line :实际运行结果为：{'errcode': 1, 'errmsg': '账号或密码错误'}
2022-08-31 15:42:03,385 whq日志 INFO test_login.py-55 line :断言成功，用例通过！
2022-08-31 15:42:03,385 whq日志 INFO test_login.py-56 line :************测试用例执行结束************
2022-08-31 15:42:03,385 whq日志 INFO test_login.py-45 line :************测试用例开始执行************
2022-08-31 15:42:03,385 whq日志 INFO test_login.py-46 line :测试数据为：{'username': 'None', 'password': 123456, 'check': '{"errcode": 1, "errmsg": "账号或密码不能为空"}'}
2022-08-31 15:42:03,385 whq日志 INFO test_login.py-48 line :实际运行结果为：{'errcode': 1, 'errmsg': '账号或密码错误'}
2022-08-31 15:42:03,386 whq日志 ERROR test_login.py-52 line :断言失败，用例失败！
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pythontest\whq\cases\test_login.py", line 50, in test_login_true
    self.assertEqual(res,eval(case["check"]))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 1144, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: {'errcode': 1, 'errmsg': '账号或密码错误'} != {'errcode': 1, 'errmsg': '账号或密码不能为空'}
- {'errcode': 1, 'errmsg': '账号或密码错误'}
?                                ^^

+ {'errcode': 1, 'errmsg': '账号或密码不能为空'}
?                                ^^^^

